/**
 * TIMELINE DATA
 * ─────────────────────────────────────────────────────────────────────────────
 * This is the single file you edit to change the timeline.
 *
 *  • YEARS: negative numbers are BCE, positive are CE.  -586 = 586 BCE, 325 = 325 CE.
 *  • ERAS:  the timeline is cut into segments, each with its own scale
 *           (pxPerYear). Deep time is compressed, recent time is stretched.
 *  • LANES: the horizontal rows. Every event belongs to exactly one lane.
 *  • EVENTS: add an object to `events`. Only `id`, `lane`, `year`, `title`
 *           are required. Use `related` to link an event to events in other
 *           lanes — those links are drawn as comparison threads on the canvas.
 *
 * Dating conventions: Mesopotamian dates follow the Middle Chronology.
 * Biblical narrative events are placed at their traditional/internal dates,
 * with alternative scholarly datings noted in the description.
 */

export type LaneId = 'world' | 'mesopotamia' | 'hebrew' | 'christian'

export interface Lane {
  id: LaneId
  name: string
  short: string
  description: string
}

export interface Era {
  id: string
  name: string
  /** Inclusive start year */
  start: number
  /** Exclusive end year */
  end: number
  /** Horizontal scale for this segment */
  pxPerYear: number
  /** Ruler tick interval in years */
  tick: number
  blurb: string
}

export interface TimelineEvent {
  id: string
  lane: LaneId
  year: number
  /** Optional end year for periods/reigns */
  endYear?: number
  /** Show "c." before the date */
  approx?: boolean
  title: string
  description?: string
  /** Text reference, e.g. "Genesis 6–9", "Sumerian King List" */
  source?: string
  /** IDs of events in other lanes to compare with */
  related?: string[]
  /**
   * Optional colour override for this single event (dot, bar, border, date).
   * Any CSS colour works; prefer a token, e.g. 'var(--lane-israel)'.
   * Used to distinguish the Northern Kingdom (Israel) from Judah.
   */
  color?: string
}

export const lanes: Lane[] = [
  {
    id: 'world',
    name: 'World & Humanity',
    short: 'World',
    description: 'Deep time, prehistory and wider world context.',
  },
  {
    id: 'mesopotamia',
    name: 'Mesopotamia',
    short: 'Mesopotamia',
    description: 'Sumer, Akkad, Babylon, Assyria and Persia — the land between the rivers.',
  },
  {
    id: 'hebrew',
    name: 'Hebrew Bible',
    short: 'Hebrew Bible',
    description: 'The narrative of Israel from Genesis to the Second Temple.',
  },
  {
    id: 'christian',
    name: 'Christ & the Church',
    short: 'Church',
    description: 'Jesus of Nazareth, the apostles and the Christian Church to the present day.',
  },
]

export const eras: Era[] = [
  {
    id: 'deep-time',
    name: 'Deep Prehistory',
    start: -450000,
    end: -12000,
    pxPerYear: 0.004,
    tick: 50000,
    blurb: 'Archaic humans, the emergence of Homo sapiens and the last Ice Age.',
  },
  {
    id: 'neolithic',
    name: 'Neolithic & First Villages',
    start: -12000,
    end: -3500,
    pxPerYear: 0.2,
    tick: 1000,
    blurb: 'Farming, the first towns and the earliest temples of southern Mesopotamia.',
  },
  {
    id: 'sumer',
    name: 'Sumer, Akkad & the Patriarchs',
    start: -3500,
    end: -1200,
    pxPerYear: 1.2,
    tick: 250,
    blurb: 'Writing, the first cities and empires; Genesis, Abraham and the Exodus.',
  },
  {
    id: 'kingdoms',
    name: 'Kingdoms, Assyria & Exile',
    start: -1200,
    end: -330,
    pxPerYear: 3,
    tick: 100,
    blurb: 'Israel and Judah between Assyria, Babylon and Persia.',
  },
  {
    id: 'second-temple',
    name: 'Second Temple & New Testament',
    start: -330,
    end: 100,
    pxPerYear: 9,
    tick: 25,
    blurb: 'Greeks and Romans in Judea; the life of Jesus and the apostolic age.',
  },
  {
    id: 'church',
    name: 'Early & Medieval Church',
    start: 100,
    end: 1500,
    pxPerYear: 2.5,
    tick: 100,
    blurb: 'Martyrs, councils, monks, schism and the long Middle Ages.',
  },
  {
    id: 'modern',
    name: 'Reformation to Today',
    start: 1500,
    end: 2030,
    pxPerYear: 8,
    tick: 25,
    blurb: 'Reformation, missions, rediscovery of the ancient Near East and the global Church.',
  },
]

export const events: TimelineEvent[] = [
  // ───────────────────────── WORLD & HUMANITY ─────────────────────────
  {
    id: 'w-heidelbergensis',
    lane: 'world',
    year: -450000,
    approx: true,
    title: 'Homo heidelbergensis',
    description:
      'Starting point of this timeline. Archaic humans spread across Africa and Europe, with early evidence of controlled fire, shelters and wooden spears.',
  },
  {
    id: 'w-neanderthal',
    lane: 'world',
    year: -400000,
    endYear: -40000,
    approx: true,
    title: 'Neanderthals in Eurasia',
    description: 'Neanderthals live across Europe and western Asia until about 40,000 years ago.',
  },
  {
    id: 'w-sapiens',
    lane: 'world',
    year: -300000,
    approx: true,
    title: 'Earliest Homo sapiens',
    description: 'Fossils from Jebel Irhoud (Morocco) are the oldest currently attributed to Homo sapiens.',
  },
  {
    id: 'w-toba',
    lane: 'world',
    year: -74000,
    approx: true,
    title: 'Toba supereruption',
    description: 'One of the largest volcanic eruptions of the last two million years, in Sumatra.',
  },
  {
    id: 'w-out-of-africa',
    lane: 'world',
    year: -60000,
    approx: true,
    title: 'Dispersal out of Africa',
    description: 'Modern humans expand into Asia, Europe and eventually Australia.',
  },
  {
    id: 'w-cave-art',
    lane: 'world',
    year: -40000,
    approx: true,
    title: 'Earliest figurative art',
    description: 'Cave paintings in Sulawesi and Europe (Chauvet c. 36,000 BCE) and carved figurines.',
  },
  {
    id: 'w-lgm',
    lane: 'world',
    year: -21000,
    approx: true,
    title: 'Last Glacial Maximum',
    description: 'Ice sheets reach their greatest extent; sea level around 120 m lower than today.',
  },
  {
    id: 'w-younger-dryas',
    lane: 'world',
    year: -10900,
    endYear: -9700,
    approx: true,
    title: 'Younger Dryas',
    description: 'A sharp return to cold conditions at the end of the Ice Age.',
  },
  {
    id: 'w-gobekli',
    lane: 'world',
    year: -9500,
    approx: true,
    title: 'Göbekli Tepe',
    description: 'Monumental stone enclosures with carved pillars in south-eastern Anatolia, built by hunter-gatherers.',
  },
  {
    id: 'w-farming',
    lane: 'world',
    year: -9000,
    approx: true,
    title: 'Farming in the Fertile Crescent',
    description: 'Domestication of wheat, barley, sheep and goats in the Levant and Zagros foothills.',
  },
  {
    id: 'w-jericho',
    lane: 'world',
    year: -8000,
    approx: true,
    title: 'Tower and wall of Jericho',
    description: 'Neolithic Jericho builds a stone tower and wall — among the oldest known fortifications.',
  },
  {
    id: 'w-catalhoyuk',
    lane: 'world',
    year: -7100,
    endYear: -5700,
    approx: true,
    title: 'Çatalhöyük',
    description: 'A large Neolithic town in Anatolia with wall paintings and household shrines.',
  },
  {
    id: 'w-copper',
    lane: 'world',
    year: -5000,
    approx: true,
    title: 'Copper metallurgy',
    description: 'Smelting of copper spreads through the Near East and the Balkans.',
  },
  {
    id: 'w-bronze',
    lane: 'world',
    year: -3300,
    approx: true,
    title: 'Bronze Age begins',
    description: 'Tin-bronze technology appears in the Near East.',
  },
  {
    id: 'w-egypt',
    lane: 'world',
    year: -3100,
    approx: true,
    title: 'Unification of Egypt',
    description: 'Narmer unites Upper and Lower Egypt; the First Dynasty begins.',
  },
  {
    id: 'w-giza',
    lane: 'world',
    year: -2560,
    approx: true,
    title: 'Great Pyramid of Giza',
    description: 'Built for Khufu during the Fourth Dynasty.',
  },
  {
    id: 'w-collapse',
    lane: 'world',
    year: -1200,
    approx: true,
    title: 'Bronze Age collapse',
    description: 'Hittite and Mycenaean states fall; the Sea Peoples attack Egypt; the Iron Age begins.',
  },
  {
    id: 'w-rome',
    lane: 'world',
    year: -753,
    title: 'Traditional founding of Rome',
    description: 'The Romans dated the founding of their city to 753 BCE.',
  },
  {
    id: 'w-alexander',
    lane: 'world',
    year: -331,
    title: 'Alexander conquers Persia',
    description: 'Victory at Gaugamela ends the Achaemenid Empire and brings Greek culture to the Near East.',
    related: ['m-seleucid'],
  },
  {
    id: 'w-augustus',
    lane: 'world',
    year: -27,
    title: 'Augustus, first Roman emperor',
    description: 'The Roman Republic gives way to the Principate.',
    related: ['c-birth'],
  },
  {
    id: 'w-rome-falls',
    lane: 'world',
    year: 476,
    title: 'End of the Western Roman Empire',
    description: 'Odoacer deposes Romulus Augustulus.',
  },
  {
    id: 'w-islam',
    lane: 'world',
    year: 622,
    title: 'Hijra; rise of Islam',
    description: 'Muhammad migrates to Medina. Within a century Islam rules from Spain to Persia.',
  },
  {
    id: 'w-printing',
    lane: 'world',
    year: 1455,
    title: 'Gutenberg Bible printed',
    description: 'Movable-type printing makes books, and soon vernacular Bibles, cheap and plentiful.',
    related: ['c-luther'],
  },
  {
    id: 'w-columbus',
    lane: 'world',
    year: 1492,
    title: 'Columbus reaches the Americas',
  },
  {
    id: 'w-french-rev',
    lane: 'world',
    year: 1789,
    title: 'French Revolution',
    description: 'Church property nationalised; the modern secular state emerges.',
  },
  {
    id: 'w-ww1',
    lane: 'world',
    year: 1914,
    endYear: 1918,
    title: 'First World War',
  },
  {
    id: 'w-ww2',
    lane: 'world',
    year: 1939,
    endYear: 1945,
    title: 'Second World War',
  },
  {
    id: 'w-israel',
    lane: 'world',
    year: 1948,
    title: 'State of Israel founded',
  },
  {
    id: 'w-web',
    lane: 'world',
    year: 1991,
    title: 'World Wide Web goes public',
  },

  // ── Natural catastrophes: eruptions, droughts, famines, pandemics ──
  // Coloured ember (--lane-disaster) so they stand out within the World lane.

  // Volcanic eruptions
  {
    id: 'w-thera',
    lane: 'world',
    year: -1600,
    approx: true,
    color: 'var(--lane-disaster)',
    title: 'Eruption of Thera (Santorini)',
    description:
      'One of the largest eruptions in human history devastates the Minoan settlement of Akrotiri and sends tsunamis across the Aegean. Its dust veil is detected in ice cores and tree rings and is often linked to the decline of Minoan Crete.',
    source: 'Volcanology; ice-core & dendrochronology',
    related: ['w-collapse'],
  },
  {
    id: 'w-vesuvius',
    lane: 'world',
    year: 79,
    color: 'var(--lane-disaster)',
    title: 'Vesuvius buries Pompeii',
    description:
      'Mount Vesuvius erupts, entombing Pompeii and Herculaneum under ash and pyroclastic flows. Pliny the Younger\u2019s letters give the first detailed eyewitness account of a major eruption.',
    source: 'Pliny the Younger, Letters 6.16, 6.20',
  },
  {
    id: 'w-536',
    lane: 'world',
    year: 536,
    endYear: 537,
    color: 'var(--lane-disaster)',
    title: 'The 536 CE dust veil — "the worst year to be alive"',
    description:
      'A mysterious fog, now traced to a massive volcanic eruption, dims the sun for over a year. Summer frosts, crop failures and famine follow across Europe and Asia, helping set the stage for the Plague of Justinian.',
    source: 'Procopius; Cassiodorus; ice-core data',
    related: ['w-justinian-plague'],
  },
  {
    id: 'w-laki',
    lane: 'world',
    year: 1783,
    endYear: 1784,
    color: 'var(--lane-disaster)',
    title: 'Laki eruption (Iceland)',
    description:
      'An eight-month fissure eruption releases a toxic haze over Europe, killing a fifth of Iceland\u2019s people and their livestock. Crop failures and hardship ripple across the continent in the following years.',
    source: 'Historical & volcanological records',
  },
  {
    id: 'w-tambora',
    lane: 'world',
    year: 1815,
    color: 'var(--lane-disaster)',
    title: 'Tambora erupts — the "Year Without a Summer"',
    description:
      'The most powerful eruption in recorded history (Indonesia) lowers global temperatures, causing snow in June, failed harvests and famine across the Northern Hemisphere in 1816.',
    source: 'Volcanology; 1816 climate records',
  },
  {
    id: 'w-krakatoa',
    lane: 'world',
    year: 1883,
    color: 'var(--lane-disaster)',
    title: 'Krakatoa explodes',
    description:
      'The eruption and its tsunamis kill tens of thousands in the Sunda Strait. The blast is heard thousands of kilometres away and vivid sunsets are seen worldwide for months.',
    source: 'Contemporary scientific reports',
  },
  {
    id: 'w-pinatubo',
    lane: 'world',
    year: 1991,
    color: 'var(--lane-disaster)',
    title: 'Mount Pinatubo (Philippines)',
    description:
      'The second-largest eruption of the 20th century injects sulfate aerosols into the stratosphere, cooling global temperatures by about 0.5 \u00b0C for a couple of years.',
    source: 'USGS / PHIVOLCS',
  },

  // Droughts & famines
  {
    id: 'w-42ka',
    lane: 'world',
    year: -2200,
    endYear: -2100,
    approx: true,
    color: 'var(--lane-disaster)',
    title: '4.2-kiloyear drought event',
    description:
      'A century-scale megadrought across the Near East, Egypt and the Indus. Widely linked to the collapse of the Akkadian Empire and Egypt\u2019s Old Kingdom.',
    source: 'Paleoclimatology; Curse of Agade',
    related: ['skl-akkad', 'w-collapse'],
  },
  {
    id: 'w-great-famine',
    lane: 'world',
    year: 1315,
    endYear: 1317,
    color: 'var(--lane-disaster)',
    title: 'Great Famine of Europe',
    description:
      'Years of relentless rain ruin harvests across northern Europe, killing millions and ending centuries of population growth just decades before the Black Death.',
    source: 'Medieval chronicles',
    related: ['w-black-death'],
  },
  {
    id: 'w-irish-famine',
    lane: 'world',
    year: 1845,
    endYear: 1852,
    color: 'var(--lane-disaster)',
    title: 'Great Irish Famine',
    description:
      'Potato blight destroys the staple crop of Ireland; roughly a million die and a million more emigrate, permanently reshaping the country\u2019s population.',
    source: 'Historical records',
  },
  {
    id: 'w-north-china-famine',
    lane: 'world',
    year: 1876,
    endYear: 1879,
    color: 'var(--lane-disaster)',
    title: 'Northern Chinese Famine',
    description:
      'A catastrophic drought-famine tied to a strong El Ni\u00f1o kills an estimated 9\u201313 million people across northern China.',
    source: 'Qing records; climate studies',
  },
  {
    id: 'w-dust-bowl',
    lane: 'world',
    year: 1930,
    endYear: 1936,
    color: 'var(--lane-disaster)',
    title: 'The Dust Bowl',
    description:
      'Severe drought and poor land use turn the American and Canadian prairies into dust storms, displacing hundreds of thousands during the Great Depression.',
    source: 'US historical records',
  },
  {
    id: 'w-bengal-famine',
    lane: 'world',
    year: 1943,
    color: 'var(--lane-disaster)',
    title: 'Bengal Famine',
    description:
      'Wartime disruption, crop shortfalls and policy failures cause a famine in British India that kills an estimated 2\u20133 million people.',
    source: 'Historical records',
  },
  {
    id: 'w-great-chinese-famine',
    lane: 'world',
    year: 1959,
    endYear: 1961,
    color: 'var(--lane-disaster)',
    title: 'Great Chinese Famine',
    description:
      'Drought combined with the policies of the Great Leap Forward produces one of the deadliest famines in history, with tens of millions of deaths.',
    source: 'Demographic studies',
  },

  // Pandemics
  {
    id: 'w-athens-plague',
    lane: 'world',
    year: -430,
    endYear: -426,
    color: 'var(--lane-disaster)',
    title: 'Plague of Athens',
    description:
      'An epidemic during the Peloponnesian War kills perhaps a third of Athens\u2019 population, including Pericles, and is described in vivid detail by Thucydides.',
    source: 'Thucydides, History 2.47–54',
  },
  {
    id: 'w-antonine-plague',
    lane: 'world',
    year: 165,
    endYear: 180,
    color: 'var(--lane-disaster)',
    title: 'Antonine Plague',
    description:
      'Probably smallpox, brought back by Roman armies from the east. It kills millions across the empire and strains Rome at its height.',
    source: 'Galen; Roman sources',
  },
  {
    id: 'w-justinian-plague',
    lane: 'world',
    year: 541,
    endYear: 549,
    color: 'var(--lane-disaster)',
    title: 'Plague of Justinian',
    description:
      'The first recorded pandemic of bubonic plague sweeps the Byzantine Empire and the Mediterranean, killing tens of millions and helping to reshape late antiquity.',
    source: 'Procopius; John of Ephesus',
    related: ['w-536'],
  },
  {
    id: 'w-black-death',
    lane: 'world',
    year: 1347,
    endYear: 1351,
    color: 'var(--lane-disaster)',
    title: 'The Black Death',
    description:
      'Bubonic plague kills an estimated 30\u201360% of Europe\u2019s population in a few years, with vast social, economic and religious consequences.',
    source: 'Medieval chronicles',
    related: ['w-great-famine'],
  },
  {
    id: 'w-columbian-smallpox',
    lane: 'world',
    year: 1520,
    color: 'var(--lane-disaster)',
    title: 'Smallpox reaches the Americas',
    description:
      'Old World diseases introduced after 1492 devastate Indigenous populations, killing a large share within a century and enabling European conquest.',
    source: 'Colonial accounts; epidemiology',
    related: ['w-columbus'],
  },
  {
    id: 'w-london-plague',
    lane: 'world',
    year: 1665,
    endYear: 1666,
    color: 'var(--lane-disaster)',
    title: 'Great Plague of London',
    description:
      'The last major English outbreak of bubonic plague kills roughly a quarter of London\u2019s population before the Great Fire of 1666.',
    source: "Samuel Pepys; Bills of Mortality",
  },
  {
    id: 'w-spanish-flu',
    lane: 'world',
    year: 1918,
    endYear: 1920,
    color: 'var(--lane-disaster)',
    title: 'Influenza pandemic ("Spanish flu")',
    description:
      'An H1N1 influenza pandemic infects a third of humanity and kills an estimated 50 million people, more than the First World War it followed.',
    source: 'Epidemiological studies',
    related: ['w-ww1'],
  },
  {
    id: 'w-hiv',
    lane: 'world',
    year: 1981,
    color: 'var(--lane-disaster)',
    title: 'HIV/AIDS pandemic recognised',
    description:
      'The first AIDS cases are reported; the pandemic has since caused tens of millions of deaths worldwide and reshaped global health.',
    source: 'CDC; WHO',
  },
  {
    id: 'w-covid',
    lane: 'world',
    year: 2020,
    endYear: 2023,
    color: 'var(--lane-disaster)',
    title: 'COVID-19 pandemic',
    description:
      'A novel coronavirus spreads worldwide, causing millions of deaths, global lockdowns and the fastest vaccine development in history.',
    source: 'WHO',
  },

  // ───────────────────────── MESOPOTAMIA ─────────────────────────

  // ── Sumerian King List: antediluvian kings ──
  // The list gives eight kings in five cities reigning a combined 241,200 years
  // before "the Flood swept over". Here the reign lengths are taken literally and
  // counted back from the Shuruppak flood layer (c. 2900 BCE), so they land in
  // deep prehistory. Move the anchor by changing these years together.
  {
    id: 'skl-alulim',
    lane: 'mesopotamia',
    year: -244100,
    endYear: -215300,
    approx: true,
    title: 'Alulim of Eridu — 28,800 years',
    description:
      '\u201cAfter the kingship descended from heaven, the kingship was in Eridu.\u201d Alulim is the first king on the list. Later tradition pairs him with Adapa, the sage who was offered immortality in heaven and refused it.',
    source: 'Sumerian King List (WB 444)',
    related: ['h-creation', 'm-kinglist'],
  },
  {
    id: 'skl-alalngar',
    lane: 'mesopotamia',
    year: -215300,
    endYear: -179300,
    approx: true,
    title: 'Alalngar of Eridu — 36,000 years',
    description: 'Second king of Eridu. With Alulim the two kings of Eridu reign 64,800 years before kingship is carried to Bad-tibira.',
    source: 'Sumerian King List (WB 444)',
  },
  {
    id: 'skl-enmenluana',
    lane: 'mesopotamia',
    year: -179300,
    endYear: -136100,
    approx: true,
    title: 'En-men-lu-ana of Bad-tibira — 43,200 years',
    description: '\u201cEridu fell and the kingship was taken to Bad-tibira.\u201d The longest single reign on the list.',
    source: 'Sumerian King List (WB 444)',
  },
  {
    id: 'skl-enmengalana',
    lane: 'mesopotamia',
    year: -136100,
    endYear: -107300,
    approx: true,
    title: 'En-men-gal-ana of Bad-tibira — 28,800 years',
    description: 'Second king of Bad-tibira.',
    source: 'Sumerian King List (WB 444)',
  },
  {
    id: 'skl-dumuzid',
    lane: 'mesopotamia',
    year: -107300,
    endYear: -71300,
    approx: true,
    title: 'Dumuzid the Shepherd — 36,000 years',
    description:
      'Third king of Bad-tibira, \u201cthe shepherd\u201d. Dumuzid is also the dying-and-rising god beloved of Inanna; as Tammuz he is still being mourned by women in Jerusalem in Ezekiel\u2019s day.',
    source: 'Sumerian King List (WB 444); Ezekiel 8:14',
    related: ['h-jeremiah'],
  },
  {
    id: 'skl-ensipadzidana',
    lane: 'mesopotamia',
    year: -71300,
    endYear: -42500,
    approx: true,
    title: 'En-sipad-zid-ana of Larak — 28,800 years',
    description: '\u201cBad-tibira fell and the kingship was taken to Larak.\u201d The only king of Larak.',
    source: 'Sumerian King List (WB 444)',
  },
  {
    id: 'skl-enmendurana',
    lane: 'mesopotamia',
    year: -42500,
    endYear: -21500,
    approx: true,
    title: 'En-men-dur-ana of Sippar — 21,000 years',
    description:
      'Seventh king before the Flood, king of Sippar, city of the sun-god. Later texts say the gods took him up to heaven and taught him the secrets of divination — frequently compared with Enoch, the seventh from Adam, who \u201cwalked with God\u201d and was taken.',
    source: 'Sumerian King List (WB 444); Genesis 5:21–24',
    related: ['h-patriarchs'],
  },
  {
    id: 'skl-ubaratutu',
    lane: 'mesopotamia',
    year: -21500,
    endYear: -2900,
    approx: true,
    title: 'Ubara-Tutu of Shuruppak — 18,600 years',
    description:
      'Last king before the Flood. In the Gilgamesh epic he is the father of Utnapishtim, the flood hero of Shuruppak; the Instructions of Shuruppak are addressed to his son. Compare Lamech, father of Noah.',
    source: 'Sumerian King List (WB 444); Gilgamesh XI',
    related: ['h-patriarchs', 'h-flood'],
  },
  {
    id: 'skl-flood',
    lane: 'mesopotamia',
    year: -2900,
    approx: true,
    title: '\u201cThen the Flood swept over\u201d',
    description:
      'The King List\u2019s dividing line. Excavations at Shuruppak (Fara), Kish and Ur found river-flood silt layers of roughly this date, though none covers all of Sumer. After it, \u201cthe kingship descended from heaven\u201d a second time, to Kish.',
    source: 'Sumerian King List (WB 444)',
    related: ['h-flood', 'm-eridu-genesis'],
  },

  // ── Sumerian King List: post-Flood dynasties (Middle Chronology) ──
  {
    id: 'skl-kish1',
    lane: 'mesopotamia',
    year: -2900,
    endYear: -2600,
    approx: true,
    title: 'First Dynasty of Kish',
    description:
      'Twenty-three kings beginning with Jushur, reigning a total of 24,510 years on the list. Kish gave later Mesopotamian rulers the title \u201cKing of Kish\u201d as a claim to rule all of Sumer and Akkad.',
    source: 'Sumerian King List',
  },
  {
    id: 'skl-etana',
    lane: 'mesopotamia',
    year: -2800,
    approx: true,
    title: 'Etana, \u201cwho ascended to heaven\u201d',
    description:
      'Thirteenth king of Kish, \u201cthe shepherd, who ascended to heaven and consolidated all the lands\u201d; the list gives him 1,500 years. The Myth of Etana tells how an eagle carried him to the sky in search of the plant of birth.',
    source: 'Sumerian King List; Myth of Etana',
    related: ['h-patriarchs'],
  },
  {
    id: 'skl-enmebaragesi',
    lane: 'mesopotamia',
    year: -2700,
    approx: true,
    title: 'Enmebaragesi of Kish',
    description:
      'The earliest king on the list confirmed by contemporary inscriptions (two vase fragments from Nippur). The list says he \u201ccarried away as spoil the weapons of Elam\u201d and reigned 900 years.',
    source: 'Sumerian King List; inscriptions from Nippur',
    related: ['m-gilgamesh-king'],
  },
  {
    id: 'skl-aga',
    lane: 'mesopotamia',
    year: -2680,
    approx: true,
    title: 'Aga of Kish',
    description:
      'Last king of the First Dynasty of Kish and son of Enmebaragesi. The poem Gilgamesh and Aga tells how he besieged Uruk and was defeated by Gilgamesh; \u201cthen Kish was defeated and the kingship was taken to Eanna\u201d (Uruk).',
    source: 'Sumerian King List; Gilgamesh and Aga',
    related: ['m-gilgamesh-king'],
  },
  {
    id: 'skl-uruk1',
    lane: 'mesopotamia',
    year: -2800,
    endYear: -2500,
    approx: true,
    title: 'First Dynasty of Uruk',
    description:
      'Meskiaggasher, \u201cson of the sun-god Utu\u201d, is followed by Enmerkar, Lugalbanda, Dumuzid the Fisherman and Gilgamesh — the heroes of the Sumerian epic cycle.',
    source: 'Sumerian King List',
  },
  {
    id: 'skl-enmerkar',
    lane: 'mesopotamia',
    year: -2750,
    approx: true,
    title: 'Enmerkar, builder of Uruk',
    description:
      '\u201cEnmerkar, the son of Meskiaggasher, the king of Uruk, who built Uruk.\u201d In the epic Enmerkar and the Lord of Aratta he is credited with inventing writing on clay and with a dispute over the confusion of languages — often set beside Nimrod, builder of Erech (Uruk), in Genesis 10.',
    source: 'Sumerian King List; Genesis 10:8–10',
    related: ['h-babel'],
  },
  {
    id: 'skl-lugalbanda',
    lane: 'mesopotamia',
    year: -2730,
    approx: true,
    title: 'Lugalbanda the Shepherd',
    description: 'Third king of Uruk, hero of two Sumerian epics and, in later tradition, father of Gilgamesh by the goddess Ninsun. The list gives him 1,200 years.',
    source: 'Sumerian King List',
  },
  {
    id: 'skl-dumuzid-fisherman',
    lane: 'mesopotamia',
    year: -2710,
    approx: true,
    title: 'Dumuzid the Fisherman',
    description: 'Fourth king of Uruk, \u201cwhose city was Kuara\u201d; he is said to have captured Enmebaragesi of Kish single-handed. A second Dumuzid, distinct from the antediluvian shepherd.',
    source: 'Sumerian King List',
    related: ['skl-dumuzid'],
  },
  {
    id: 'skl-ur1',
    lane: 'mesopotamia',
    year: -2600,
    endYear: -2500,
    approx: true,
    title: 'First Dynasty of Ur: Mesannepada',
    description:
      '\u201cUruk was defeated and the kingship was taken to Ur.\u201d Mesannepada is attested by his own seals and by a bead found at Mari. Meskalamdug and Akalamdug, known from the Royal Tombs of Ur, belong to this house though the list omits them.',
    source: 'Sumerian King List; inscriptions',
    related: ['m-ur-tombs'],
  },
  {
    id: 'skl-lugalannemundu',
    lane: 'mesopotamia',
    year: -2400,
    approx: true,
    title: 'Lugal-Anne-Mundu of Adab',
    description: 'The sole king of the dynasty of Adab, credited with 90 years and, in a later inscription, with an empire \u201cfrom the Lower Sea to the Upper Sea\u201d.',
    source: 'Sumerian King List',
  },
  {
    id: 'skl-kubaba',
    lane: 'mesopotamia',
    year: -2400,
    approx: true,
    title: 'Kug-Bau (Kubaba), queen of Kish',
    description:
      '\u201cThe woman tavern-keeper, who made firm the foundations of Kish\u201d — the only woman on the King List, ruling alone for 100 years as the Third Dynasty of Kish. Later worshipped as a goddess in Anatolia.',
    source: 'Sumerian King List',
  },
  {
    id: 'skl-lugalzagesi',
    lane: 'mesopotamia',
    year: -2358,
    endYear: -2334,
    title: 'Lugal-zage-si of Uruk',
    description:
      'Third Dynasty of Uruk. From Umma he conquered Lagash and Uruk and claimed rule from the Persian Gulf to the Mediterranean, before being defeated and led in a neck-stock to Nippur by Sargon of Akkad.',
    source: 'Sumerian King List; Sargon inscriptions',
    related: ['m-sargon'],
  },
  {
    id: 'skl-akkad',
    lane: 'mesopotamia',
    year: -2334,
    endYear: -2154,
    title: 'Dynasty of Akkad',
    description:
      'Sargon, Rimush, Manishtushu, Naram-Sin and Shar-kali-sharri. After the last comes the list\u2019s famous line: \u201cWho was king? Who was not king?\u201d — a time of anarchy before Dudu and Shu-turul.',
    source: 'Sumerian King List',
    related: ['m-sargon'],
  },
  {
    id: 'skl-naramsin',
    lane: 'mesopotamia',
    year: -2254,
    endYear: -2218,
    title: 'Naram-Sin of Akkad',
    description:
      'Grandson of Sargon, the first Mesopotamian king to call himself a god and \u201cKing of the Four Quarters\u201d. The later Curse of Agade blames the empire\u2019s fall on his sack of Enlil\u2019s temple at Nippur.',
    source: 'Sumerian King List; Curse of Agade',
  },
  {
    id: 'skl-gutians',
    lane: 'mesopotamia',
    year: -2154,
    endYear: -2055,
    approx: true,
    title: 'Gutian dynasty',
    description: '\u201cThe army of Gutium, a king whose name is unknown.\u201d Twenty-one Gutian rulers from the Zagros mountains hold Sumer after the fall of Akkad, remembered as barbarians in later literature.',
    source: 'Sumerian King List',
  },
  {
    id: 'skl-utuhengal',
    lane: 'mesopotamia',
    year: -2055,
    endYear: -2048,
    approx: true,
    title: 'Utu-hengal of Uruk drives out the Gutians',
    description: 'Fifth Dynasty of Uruk, a single king. His victory inscription describes defeating Tirigan, last king of Gutium, and \u201creturning the kingship of Sumer into its own hands\u201d.',
    source: 'Sumerian King List; Utu-hengal victory stele',
    related: ['m-ur3'],
  },
  {
    id: 'skl-shulgi',
    lane: 'mesopotamia',
    year: -2094,
    endYear: -2047,
    title: 'Shulgi of Ur',
    description:
      'Second king of the Third Dynasty of Ur (Ur-Nammu, Shulgi, Amar-Sin, Shu-Sin, Ibbi-Sin). Shulgi reformed the calendar, weights and scribal schools, was deified in his lifetime, and boasted of running from Nippur to Ur and back in a day.',
    source: 'Sumerian King List; royal hymns',
    related: ['m-ur3'],
  },
  {
    id: 'skl-ibbisin',
    lane: 'mesopotamia',
    year: -2028,
    endYear: -2004,
    title: 'Ibbi-Sin; fall of Ur',
    description:
      'Last king of Ur III. Famine, Amorite incursions and the defection of his general Ishbi-Erra end in the sack of Ur by the Elamites, mourned in the Lamentation over the Destruction of Ur.',
    source: 'Sumerian King List; Lament for Ur',
    related: ['h-abraham'],
  },
  {
    id: 'skl-isin',
    lane: 'mesopotamia',
    year: -2017,
    endYear: -1794,
    title: 'Dynasty of Isin',
    description:
      '\u201cUr was defeated and the kingship was taken to Isin.\u201d Ishbi-Erra and his successors down to Damiq-ilishu. The King List was compiled and copied under Isin, whose scribes cast their dynasty as heir to all the kingships since Eridu.',
    source: 'Sumerian King List',
    related: ['m-kinglist'],
  },

  {
    id: 'm-ubaid',
    lane: 'mesopotamia',
    year: -5500,
    endYear: -4000,
    approx: true,
    title: 'Ubaid culture; temples at Eridu',
    description:
      'Farming villages spread across southern Mesopotamia. At Eridu a sequence of temples is rebuilt on the same spot for millennia — Sumerian tradition called Eridu the first city.',
  },
  {
    id: 'm-uruk',
    lane: 'mesopotamia',
    year: -4000,
    endYear: -3100,
    approx: true,
    title: 'Uruk period: the first cities',
    description: 'Uruk grows to perhaps 40,000 people, with monumental temples, cylinder seals and mass-produced pottery.',
  },
  {
    id: 'm-writing',
    lane: 'mesopotamia',
    year: -3200,
    approx: true,
    title: 'Cuneiform writing invented',
    description: 'Accounting tablets at Uruk develop into the world\u2019s first writing system.',
  },
  {
    id: 'm-early-dynastic',
    lane: 'mesopotamia',
    year: -2900,
    endYear: -2350,
    approx: true,
    title: 'Early Dynastic Sumer',
    description: 'City-states such as Kish, Ur, Lagash and Uruk compete for hegemony.',
  },
  {
    id: 'm-gilgamesh-king',
    lane: 'mesopotamia',
    year: -2700,
    approx: true,
    title: 'Gilgamesh, king of Uruk',
    description: 'The historical king behind the later epic; the Sumerian King List places him in the first dynasty of Uruk.',
  },
  {
    id: 'm-ur-tombs',
    lane: 'mesopotamia',
    year: -2600,
    approx: true,
    title: 'Royal Tombs of Ur',
    description: 'Lavish burials (Puabi, the Standard of Ur) excavated by Leonard Woolley in the 1920s.',
    related: ['m-woolley'],
  },
  {
    id: 'm-sargon',
    lane: 'mesopotamia',
    year: -2334,
    endYear: -2279,
    title: 'Sargon of Akkad',
    description: 'Founds the Akkadian Empire, the first to unite Sumer and Akkad under one ruler.',
  },
  {
    id: 'm-ur3',
    lane: 'mesopotamia',
    year: -2112,
    endYear: -2004,
    title: 'Third Dynasty of Ur',
    description:
      'Ur-Nammu and Shulgi rule a centralised Sumerian state and build the Great Ziggurat of Ur. Genesis says Abraham\u2019s family set out from \u201cUr of the Chaldeans\u201d.',
    source: 'Genesis 11:28–31',
    related: ['h-abraham', 'h-babel'],
  },
  {
    id: 'm-ur-nammu',
    lane: 'mesopotamia',
    year: -2100,
    approx: true,
    title: 'Code of Ur-Nammu',
    description: 'The oldest surviving law code, written in Sumerian, with fines for bodily injury.',
    related: ['h-torah'],
  },
  {
    id: 'm-kinglist',
    lane: 'mesopotamia',
    year: -2000,
    approx: true,
    title: 'Sumerian King List',
    description:
      'Lists kings before and after \u201cthe Flood swept over\u201d. Antediluvian kings reign for tens of thousands of years — compare the long lifespans of Genesis 5.',
    source: 'Weld-Blundell Prism',
    related: ['h-patriarchs', 'h-flood'],
  },
  {
    id: 'm-gilgamesh-ob',
    lane: 'mesopotamia',
    year: -1800,
    approx: true,
    title: 'Old Babylonian Gilgamesh tablets',
    description: 'The earliest Akkadian versions of the Gilgamesh poems.',
  },
  {
    id: 'm-hammurabi',
    lane: 'mesopotamia',
    year: -1792,
    endYear: -1750,
    title: 'Hammurabi of Babylon; Law Code',
    description:
      'Babylon becomes the capital of Mesopotamia. Hammurabi\u2019s stele contains 282 laws including \u201can eye for an eye\u201d — a principle also found in Exodus 21.',
    source: 'Louvre stele Sb 8',
    related: ['h-torah'],
  },
  {
    id: 'm-atrahasis',
    lane: 'mesopotamia',
    year: -1700,
    approx: true,
    title: 'Atrahasis epic',
    description:
      'Akkadian account of the creation of humans from clay and a flood sent by the gods; the hero Atrahasis builds a boat and survives.',
    related: ['h-flood', 'h-creation'],
  },
  {
    id: 'm-eridu-genesis',
    lane: 'mesopotamia',
    year: -1600,
    approx: true,
    title: 'Sumerian Flood story (Eridu Genesis)',
    description: 'Ziusudra, king of Shuruppak, is warned of the flood and saved in a great boat.',
    related: ['h-flood'],
  },
  {
    id: 'm-kassite',
    lane: 'mesopotamia',
    year: -1595,
    endYear: -1155,
    title: 'Kassite dynasty of Babylon',
    description: 'A long period of stability; Babylonian becomes the diplomatic language of the Near East.',
  },
  {
    id: 'm-enuma-elish',
    lane: 'mesopotamia',
    year: -1200,
    approx: true,
    title: 'Enūma Eliš, the Babylonian creation epic',
    description:
      'Marduk defeats the sea-goddess Tiamat and forms the heavens and earth from her body, then creates humanity. Recited at the Babylonian New Year festival. Dating is disputed (c. 1700–1100 BCE).',
    related: ['h-creation'],
  },
  {
    id: 'm-gilgamesh-sb',
    lane: 'mesopotamia',
    year: -1200,
    approx: true,
    title: 'Standard Babylonian Epic of Gilgamesh',
    description:
      'Edited by Sîn-lēqi-unninni. Tablet XI retells the flood: Utnapishtim builds a boat, saves animals, releases birds, and offers sacrifice on a mountain.',
    related: ['h-flood'],
  },
  {
    id: 'm-assyria',
    lane: 'mesopotamia',
    year: -911,
    endYear: -609,
    title: 'Neo-Assyrian Empire',
    description: 'From Ashur and Nimrud, Assyria dominates the Near East for three centuries.',
  },
  {
    id: 'm-qarqar',
    lane: 'mesopotamia',
    year: -853,
    title: 'Battle of Qarqar; Kurkh Monolith',
    description: 'Shalmaneser III\u2019s inscription names \u201cAhab the Israelite\u201d among a coalition of kings.',
    related: ['h-elijah'],
  },
  {
    id: 'm-black-obelisk',
    lane: 'mesopotamia',
    year: -841,
    title: 'Black Obelisk: Jehu pays tribute',
    description: 'The only surviving image of an Israelite king — Jehu bowing before Shalmaneser III.',
    related: ['h-jehu'],
  },
  {
    id: 'm-samaria',
    lane: 'mesopotamia',
    year: -722,
    title: 'Assyria captures Samaria',
    description: 'Shalmaneser V and Sargon II end the kingdom of Israel and deport its population.',
    related: ['h-fall-samaria'],
  },
  {
    id: 'm-sennacherib',
    lane: 'mesopotamia',
    year: -701,
    title: 'Sennacherib\u2019s campaign; Lachish reliefs',
    description:
      'Sennacherib\u2019s Prism describes shutting up Hezekiah \u201clike a caged bird\u201d in Jerusalem — but does not claim to have taken the city.',
    related: ['h-hezekiah'],
  },
  {
    id: 'm-ashurbanipal',
    lane: 'mesopotamia',
    year: -668,
    endYear: -631,
    title: 'Ashurbanipal\u2019s library at Nineveh',
    description: 'Some 30,000 tablets, including the copies of Gilgamesh and Enūma Eliš read today.',
  },
  {
    id: 'm-nineveh',
    lane: 'mesopotamia',
    year: -612,
    title: 'Fall of Nineveh',
    description: 'Babylonians and Medes destroy the Assyrian capital, as the prophet Nahum had announced.',
    source: 'Nahum 1–3',
  },
  {
    id: 'm-nebuchadnezzar',
    lane: 'mesopotamia',
    year: -605,
    endYear: -562,
    title: 'Nebuchadnezzar II',
    description: 'Rebuilds Babylon with the Ishtar Gate and hanging gardens; deports Judah\u2019s elite after 597 and 586.',
    related: ['h-exile', 'h-jerusalem-fall'],
  },
  {
    id: 'm-etemenanki',
    lane: 'mesopotamia',
    year: -600,
    approx: true,
    title: 'Etemenanki ziggurat rebuilt',
    description:
      'Nebuchadnezzar completes the great ziggurat of Marduk, \u201cHouse of the foundation of heaven and earth\u201d — often connected with the Tower of Babel.',
    related: ['h-babel'],
  },
  {
    id: 'm-cyrus',
    lane: 'mesopotamia',
    year: -539,
    title: 'Cyrus takes Babylon; Cyrus Cylinder',
    description: 'The Persian king enters Babylon without a battle and allows deported peoples to return home.',
    related: ['h-return'],
  },
  {
    id: 'm-persia',
    lane: 'mesopotamia',
    year: -539,
    endYear: -331,
    title: 'Achaemenid Persia rules Mesopotamia',
  },
  {
    id: 'm-xerxes',
    lane: 'mesopotamia',
    year: -486,
    endYear: -465,
    title: 'Xerxes I',
    description: 'Generally identified with Ahasuerus in the book of Esther.',
    related: ['h-esther'],
  },
  {
    id: 'm-seleucid',
    lane: 'mesopotamia',
    year: -312,
    title: 'Seleucid dynasty; Babylon declines',
    description: 'Seleucus I founds Seleucia on the Tigris; Babylon slowly empties.',
  },
  {
    id: 'm-talmud',
    lane: 'mesopotamia',
    year: 500,
    approx: true,
    title: 'Babylonian Talmud completed',
    description: 'Jewish academies at Sura and Pumbedita, in the old Babylonian heartland, finish the Talmud.',
  },
  {
    id: 'm-decipherment',
    lane: 'mesopotamia',
    year: 1857,
    title: 'Cuneiform deciphered',
    description: 'Rawlinson, Hincks, Oppert and Fox Talbot independently translate the same Assyrian text.',
  },
  {
    id: 'm-george-smith',
    lane: 'mesopotamia',
    year: 1872,
    title: 'George Smith reads the Babylonian flood tablet',
    description:
      'Working in the British Museum on tablets from Nineveh, Smith announces a Babylonian flood story strikingly like Genesis.',
    related: ['h-flood', 'm-gilgamesh-sb'],
  },
  {
    id: 'm-woolley',
    lane: 'mesopotamia',
    year: 1922,
    endYear: 1934,
    title: 'Woolley excavates Ur',
    description: 'Uncovers the Royal Tombs and the ziggurat, bringing Sumer to public attention.',
  },

  // ───────────────────────── HEBREW BIBLE ─────────────────────────
  {
    id: 'h-creation',
    lane: 'hebrew',
    year: -4000,
    approx: true,
    title: 'Creation (Genesis 1–2)',
    description:
      'Placed here at its traditional date (Ussher 4004 BCE; the Hebrew calendar counts from 3761 BCE). Genesis 1 orders creation in six days and a Sabbath — compare the Babylonian Enūma Eliš, where Marduk shapes the cosmos from the sea-goddess Tiamat.',
    source: 'Genesis 1–2',
    related: ['m-enuma-elish', 'm-atrahasis'],
  },
  {
    id: 'h-patriarchs',
    lane: 'hebrew',
    year: -3900,
    endYear: -2350,
    approx: true,
    title: 'Antediluvian generations (Genesis 5)',
    description:
      'Adam to Noah, with lifespans up to 969 years — compare the Sumerian King List\u2019s kings reigning for thousands of years before the Flood.',
    source: 'Genesis 5',
    related: ['m-kinglist'],
  },
  {
    id: 'h-flood',
    lane: 'hebrew',
    year: -2350,
    approx: true,
    title: 'The Flood (Genesis 6–9)',
    description:
      'Noah builds the ark, saves the animals, releases a raven and a dove, lands on the mountains of Ararat and offers sacrifice. Parallels: Ziusudra (Sumerian), Atrahasis and Utnapishtim (Akkadian). Traditional date 2348 BCE (Ussher).',
    source: 'Genesis 6–9',
    related: ['m-eridu-genesis', 'm-atrahasis', 'm-gilgamesh-sb', 'm-kinglist'],
  },
  {
    id: 'h-babel',
    lane: 'hebrew',
    year: -2200,
    approx: true,
    title: 'Tower of Babel (Genesis 11)',
    description:
      'Humanity builds a tower of baked brick and bitumen \u201cwith its top in the heavens\u201d in the land of Shinar (Sumer). Ziggurats such as those of Ur and Babylon (Etemenanki) are the obvious background.',
    source: 'Genesis 11:1–9',
    related: ['m-etemenanki', 'm-ur3'],
  },
  {
    id: 'h-abraham',
    lane: 'hebrew',
    year: -2000,
    approx: true,
    title: 'Abraham leaves Ur and Haran',
    description:
      'Terah\u2019s family moves from Ur of the Chaldeans to Haran; Abram is called to Canaan. Traditional date c. 2091 BCE — during the Third Dynasty of Ur.',
    source: 'Genesis 11:31–12:5',
    related: ['m-ur3'],
  },
  {
    id: 'h-isaac-jacob',
    lane: 'hebrew',
    year: -1900,
    endYear: -1700,
    approx: true,
    title: 'Isaac, Jacob and the twelve sons',
    source: 'Genesis 21–50',
  },
  {
    id: 'h-joseph',
    lane: 'hebrew',
    year: -1700,
    approx: true,
    title: 'Joseph in Egypt',
    description: 'Sold into Egypt, Joseph rises to power and brings his family there during famine.',
    source: 'Genesis 37–50',
  },
  {
    id: 'h-exodus',
    lane: 'hebrew',
    year: -1446,
    approx: true,
    title: 'The Exodus',
    description:
      'Moses leads Israel out of Egypt. Traditional \u201cearly date\u201d 1446 BCE (from 1 Kings 6:1); many scholars prefer a \u201clate date\u201d c. 1250 BCE under Ramesses II.',
    source: 'Exodus 1–15',
  },
  {
    id: 'h-torah',
    lane: 'hebrew',
    year: -1446,
    endYear: -1406,
    approx: true,
    title: 'Law at Sinai; wilderness years',
    description:
      'The Ten Commandments and the covenant code. Casuistic \u201cif\u2026then\u201d laws and the lex talionis resemble the earlier codes of Ur-Nammu and Hammurabi, yet differ in theology and in valuing persons over property.',
    source: 'Exodus 19–24; Leviticus; Deuteronomy',
    related: ['m-hammurabi', 'm-ur-nammu'],
  },
  {
    id: 'h-conquest',
    lane: 'hebrew',
    year: -1406,
    endYear: -1375,
    approx: true,
    title: 'Joshua enters Canaan',
    source: 'Joshua',
  },
  {
    id: 'h-judges',
    lane: 'hebrew',
    year: -1375,
    endYear: -1050,
    approx: true,
    title: 'Period of the Judges',
    description: 'Deborah, Gideon, Samson, Ruth and Samuel.',
    source: 'Judges; Ruth; 1 Samuel 1–7',
  },
  {
    id: 'h-merneptah',
    lane: 'hebrew',
    year: -1208,
    title: 'Merneptah Stele names \u201cIsrael\u201d',
    description: 'The earliest extra-biblical mention of Israel, as a people in Canaan.',
  },
  {
    id: 'h-saul',
    lane: 'hebrew',
    year: -1050,
    endYear: -1010,
    approx: true,
    title: 'Saul, first king of Israel',
    source: '1 Samuel 8–31',
  },
  {
    id: 'h-david',
    lane: 'hebrew',
    year: -1010,
    endYear: -970,
    approx: true,
    title: 'David, king in Jerusalem',
    description: 'The Tel Dan Stele (9th c.) mentions the \u201cHouse of David\u201d.',
    source: '2 Samuel; 1 Chronicles',
  },
  {
    id: 'h-solomon',
    lane: 'hebrew',
    year: -970,
    endYear: -931,
    approx: true,
    title: 'Solomon; First Temple built',
    description: 'Temple construction begins c. 966 BCE.',
    source: '1 Kings 1–11',
  },
  {
    id: 'h-divided',
    lane: 'hebrew',
    year: -931,
    approx: true,
    title: 'Kingdom divides: Israel and Judah',
    description:
      'After Solomon, ten northern tribes secede under Jeroboam to form Israel (capital eventually Samaria); Judah and Benjamin — the two southern tribes — keep the house of David in Jerusalem.',
    source: '1 Kings 12',
  },

  // ─── Kings of the Northern Kingdom (Israel, 10 tribes) ───
  // Coloured with --lane-israel (light rose). Dates follow Thiele\u2019s chronology.
  {
    id: 'isr-jeroboam1',
    lane: 'hebrew',
    year: -931,
    endYear: -910,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Jeroboam I (Israel)',
    description: 'First king of the north; sets up golden calves at Bethel and Dan so pilgrims need not go to Jerusalem.',
    source: '1 Kings 12–14',
  },
  {
    id: 'isr-nadab',
    lane: 'hebrew',
    year: -910,
    endYear: -909,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Nadab (Israel)',
    description: 'Son of Jeroboam; assassinated by Baasha while besieging Gibbethon.',
    source: '1 Kings 15',
  },
  {
    id: 'isr-baasha',
    lane: 'hebrew',
    year: -909,
    endYear: -886,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Baasha (Israel)',
    description: 'Wipes out the house of Jeroboam and wars with Asa of Judah.',
    source: '1 Kings 15–16',
  },
  {
    id: 'isr-elah',
    lane: 'hebrew',
    year: -886,
    endYear: -885,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Elah (Israel)',
    description: 'Son of Baasha; murdered while drunk by his chariot commander Zimri.',
    source: '1 Kings 16',
  },
  {
    id: 'isr-zimri',
    lane: 'hebrew',
    year: -885,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Zimri (Israel) — 7 days',
    description: 'Reigns a week in Tirzah, then burns the palace over himself when Omri\u2019s troops storm the city.',
    source: '1 Kings 16',
  },
  {
    id: 'isr-tibni',
    lane: 'hebrew',
    year: -885,
    endYear: -880,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Tibni (Israel) — rival',
    description: 'Half the people follow Tibni against Omri for several years before Omri prevails.',
    source: '1 Kings 16:21–22',
  },
  {
    id: 'isr-omri',
    lane: 'hebrew',
    year: -885,
    endYear: -874,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Omri (Israel)',
    description: 'Founds Samaria as the capital. So important that Assyria long called Israel \u201cthe House of Omri\u201d.',
    source: '1 Kings 16; Mesha Stele',
  },
  {
    id: 'isr-ahab',
    lane: 'hebrew',
    year: -874,
    endYear: -853,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Ahab (Israel)',
    description: 'Marries Jezebel of Tyre; opposed by Elijah. First Israelite king named in an Assyrian inscription (Qarqar).',
    source: '1 Kings 16–22',
    related: ['m-qarqar'],
  },
  {
    id: 'isr-ahaziah',
    lane: 'hebrew',
    year: -853,
    endYear: -852,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Ahaziah (Israel)',
    description: 'Son of Ahab; dies after a fall, having sent to Baal-zebub of Ekron.',
    source: '1 Kings 22; 2 Kings 1',
  },
  {
    id: 'isr-joram',
    lane: 'hebrew',
    year: -852,
    endYear: -841,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Joram / Jehoram (Israel)',
    description: 'Last of the Omride line; killed by Jehu at Jezreel.',
    source: '2 Kings 3–9',
  },
  {
    id: 'isr-jehu',
    lane: 'hebrew',
    year: -841,
    endYear: -814,
    color: 'var(--lane-israel)',
    title: 'Jehu (Israel)',
    description: 'Exterminates the house of Ahab and the priests of Baal; pays tribute to Shalmaneser III on the Black Obelisk.',
    source: '2 Kings 9–10',
    related: ['m-black-obelisk'],
  },
  {
    id: 'isr-jehoahaz',
    lane: 'hebrew',
    year: -814,
    endYear: -798,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Jehoahaz (Israel)',
    description: 'Oppressed by Hazael of Aram; the army reduced to almost nothing.',
    source: '2 Kings 13',
  },
  {
    id: 'isr-jehoash',
    lane: 'hebrew',
    year: -798,
    endYear: -782,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Jehoash / Joash (Israel)',
    description: 'Recovers cities from Aram; defeats Amaziah of Judah and breaks down Jerusalem\u2019s wall.',
    source: '2 Kings 13–14',
  },
  {
    id: 'isr-jeroboam2',
    lane: 'hebrew',
    year: -782,
    endYear: -753,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Jeroboam II (Israel)',
    description: 'Long, prosperous reign restoring Israel\u2019s borders; the age of Amos and Hosea, who denounce its injustice.',
    source: '2 Kings 14; Amos; Hosea',
  },
  {
    id: 'isr-zechariah',
    lane: 'hebrew',
    year: -753,
    endYear: -752,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Zechariah (Israel) — 6 months',
    description: 'Last of the house of Jehu; assassinated by Shallum, ending the dynasty as prophesied.',
    source: '2 Kings 15',
  },
  {
    id: 'isr-shallum',
    lane: 'hebrew',
    year: -752,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Shallum (Israel) — 1 month',
    description: 'Reigns one month in Samaria before Menahem kills him.',
    source: '2 Kings 15',
  },
  {
    id: 'isr-menahem',
    lane: 'hebrew',
    year: -752,
    endYear: -742,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Menahem (Israel)',
    description: 'Buys off Tiglath-Pileser III (\u201cPul\u201d) of Assyria with a thousand talents of silver levied on the wealthy.',
    source: '2 Kings 15',
    related: ['m-assyria'],
  },
  {
    id: 'isr-pekahiah',
    lane: 'hebrew',
    year: -742,
    endYear: -740,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Pekahiah (Israel)',
    description: 'Son of Menahem; killed by his officer Pekah.',
    source: '2 Kings 15',
  },
  {
    id: 'isr-pekah',
    lane: 'hebrew',
    year: -740,
    endYear: -732,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Pekah (Israel)',
    description: 'Joins Aram against Judah (the Syro-Ephraimite war); Tiglath-Pileser III annexes Galilee and deports its people.',
    source: '2 Kings 15–16; Isaiah 7',
    related: ['m-assyria'],
  },
  {
    id: 'isr-hoshea',
    lane: 'hebrew',
    year: -732,
    endYear: -722,
    approx: true,
    color: 'var(--lane-israel)',
    title: 'Hoshea (Israel) — last king',
    description: 'Rebels against Assyria and appeals to Egypt; Samaria falls after a three-year siege and the north is deported.',
    source: '2 Kings 17',
    related: ['m-samaria', 'h-fall-samaria'],
  },

  // ─── Kings of the Southern Kingdom (Judah + Benjamin, 2 tribes) ───
  // Coloured with --lane-judah (light lapis). The unbroken house of David.
  {
    id: 'jud-rehoboam',
    lane: 'hebrew',
    year: -931,
    endYear: -913,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Rehoboam (Judah)',
    description: 'Solomon\u2019s son, whose harshness splits the kingdom. Shishak of Egypt plunders Jerusalem in his fifth year.',
    source: '1 Kings 12–14; 2 Chronicles 10–12',
  },
  {
    id: 'jud-abijah',
    lane: 'hebrew',
    year: -913,
    endYear: -911,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Abijah / Abijam (Judah)',
    description: 'Wars with Jeroboam of Israel and defeats him.',
    source: '1 Kings 15; 2 Chronicles 13',
  },
  {
    id: 'jud-asa',
    lane: 'hebrew',
    year: -911,
    endYear: -870,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Asa (Judah)',
    description: 'Reforming king who removes idols; makes a treaty with Aram against Baasha of Israel.',
    source: '1 Kings 15; 2 Chronicles 14–16',
  },
  {
    id: 'jud-jehoshaphat',
    lane: 'hebrew',
    year: -870,
    endYear: -848,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Jehoshaphat (Judah)',
    description: 'Allies with Ahab by marriage; sends judges and Levites to teach the Law through the towns.',
    source: '1 Kings 22; 2 Chronicles 17–20',
  },
  {
    id: 'jud-jehoram',
    lane: 'hebrew',
    year: -848,
    endYear: -841,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Jehoram / Joram (Judah)',
    description: 'Marries Athaliah of the house of Ahab; Edom and Libnah revolt.',
    source: '2 Kings 8; 2 Chronicles 21',
  },
  {
    id: 'jud-ahaziah',
    lane: 'hebrew',
    year: -841,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Ahaziah (Judah) — 1 year',
    description: 'Nephew of Joram of Israel; killed alongside him in Jehu\u2019s purge.',
    source: '2 Kings 8–9; 2 Chronicles 22',
  },
  {
    id: 'jud-athaliah',
    lane: 'hebrew',
    year: -841,
    endYear: -835,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Athaliah (Judah) — queen',
    description: 'Ahab\u2019s daughter seizes the throne and kills the royal heirs; the infant Joash is hidden in the Temple.',
    source: '2 Kings 11; 2 Chronicles 22–23',
  },
  {
    id: 'jud-joash',
    lane: 'hebrew',
    year: -835,
    endYear: -796,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Joash / Jehoash (Judah)',
    description: 'Crowned at seven by the priest Jehoiada; repairs the Temple, then declines after Jehoiada\u2019s death.',
    source: '2 Kings 12; 2 Chronicles 24',
  },
  {
    id: 'jud-amaziah',
    lane: 'hebrew',
    year: -796,
    endYear: -767,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Amaziah (Judah)',
    description: 'Defeats Edom, then provokes Jehoash of Israel and is defeated; Jerusalem\u2019s wall is breached.',
    source: '2 Kings 14; 2 Chronicles 25',
  },
  {
    id: 'jud-uzziah',
    lane: 'hebrew',
    year: -767,
    endYear: -740,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Uzziah / Azariah (Judah)',
    description: 'Long, strong reign; struck with leprosy after usurping priestly duties. Isaiah is called \u201cin the year King Uzziah died\u201d.',
    source: '2 Kings 15; 2 Chronicles 26; Isaiah 6',
  },
  {
    id: 'jud-jotham',
    lane: 'hebrew',
    year: -740,
    endYear: -732,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Jotham (Judah)',
    description: 'Builds the upper gate of the Temple; faces the rising threat of Aram and Israel.',
    source: '2 Kings 15; 2 Chronicles 27',
  },
  {
    id: 'jud-ahaz',
    lane: 'hebrew',
    year: -732,
    endYear: -716,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Ahaz (Judah)',
    description: 'Appeals to Assyria against Aram and Israel despite Isaiah\u2019s warning; introduces a foreign altar.',
    source: '2 Kings 16; Isaiah 7; 2 Chronicles 28',
    related: ['m-assyria'],
  },
  {
    id: 'jud-hezekiah',
    lane: 'hebrew',
    year: -716,
    endYear: -687,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Hezekiah (Judah)',
    description: 'Great reformer; cuts the Siloam tunnel and withstands Sennacherib\u2019s siege of 701, when Jerusalem is spared.',
    source: '2 Kings 18–20; Isaiah 36–39',
    related: ['m-sennacherib', 'h-hezekiah'],
  },
  {
    id: 'jud-manasseh',
    lane: 'hebrew',
    year: -687,
    endYear: -643,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Manasseh (Judah)',
    description: 'Longest-reigning king of Judah; remembered for idolatry, later for repentance. Vassal of Assyria.',
    source: '2 Kings 21; 2 Chronicles 33',
  },
  {
    id: 'jud-amon',
    lane: 'hebrew',
    year: -643,
    endYear: -641,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Amon (Judah)',
    description: 'Continues his father\u2019s idolatry; assassinated by his servants.',
    source: '2 Kings 21; 2 Chronicles 33',
  },
  {
    id: 'jud-josiah',
    lane: 'hebrew',
    year: -641,
    endYear: -609,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Josiah (Judah)',
    description: 'The great reformer; a book of the Law is found in the Temple. Killed at Megiddo facing Pharaoh Necho.',
    source: '2 Kings 22–23; 2 Chronicles 34–35',
    related: ['h-josiah'],
  },
  {
    id: 'jud-jehoahaz',
    lane: 'hebrew',
    year: -609,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Jehoahaz (Judah) — 3 months',
    description: 'Deposed by Pharaoh Necho after three months and taken to Egypt.',
    source: '2 Kings 23; 2 Chronicles 36',
  },
  {
    id: 'jud-jehoiakim',
    lane: 'hebrew',
    year: -609,
    endYear: -598,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Jehoiakim (Judah)',
    description: 'Set up by Egypt, then vassal of Babylon; burns Jeremiah\u2019s scroll and rebels against Nebuchadnezzar.',
    source: '2 Kings 23–24; Jeremiah 36',
  },
  {
    id: 'jud-jehoiachin',
    lane: 'hebrew',
    year: -598,
    endYear: -597,
    approx: true,
    color: 'var(--lane-judah)',
    title: 'Jehoiachin (Judah) — 3 months',
    description: 'Surrenders Jerusalem and is deported to Babylon in 597; his rations there appear on Babylonian tablets.',
    source: '2 Kings 24; Jeremiah 52',
    related: ['h-first-deportation'],
  },
  {
    id: 'jud-zedekiah',
    lane: 'hebrew',
    year: -597,
    endYear: -586,
    color: 'var(--lane-judah)',
    title: 'Zedekiah (Judah) — last king',
    description: 'Last king of Judah; rebels against Babylon. Jerusalem and the Temple are destroyed in 586 and he is blinded and exiled.',
    source: '2 Kings 24–25; Jeremiah 39',
    related: ['h-jerusalem-fall'],
  },

  {
    id: 'h-elijah',
    lane: 'hebrew',
    year: -870,
    approx: true,
    title: 'Elijah confronts Ahab',
    description: 'Ahab (c. 874–853) is the first Israelite king named in an Assyrian inscription.',
    source: '1 Kings 17–21',
    related: ['m-qarqar'],
  },
  {
    id: 'h-jehu',
    lane: 'hebrew',
    year: -841,
    title: 'Jehu\u2019s coup',
    description: 'Jehu destroys the house of Ahab and submits to Assyria.',
    source: '2 Kings 9–10',
    related: ['m-black-obelisk'],
  },
  {
    id: 'h-amos',
    lane: 'hebrew',
    year: -760,
    approx: true,
    title: 'Amos and Hosea prophesy',
    source: 'Amos; Hosea',
  },
  {
    id: 'h-isaiah',
    lane: 'hebrew',
    year: -740,
    endYear: -690,
    approx: true,
    title: 'Isaiah in Jerusalem',
    source: 'Isaiah 1–39',
  },
  {
    id: 'h-fall-samaria',
    lane: 'hebrew',
    year: -722,
    title: 'Fall of Samaria; end of Israel',
    source: '2 Kings 17',
    related: ['m-samaria'],
  },
  {
    id: 'h-hezekiah',
    lane: 'hebrew',
    year: -701,
    title: 'Hezekiah and the siege of Jerusalem',
    description: 'Sennacherib\u2019s army withdraws; Jerusalem is spared.',
    source: '2 Kings 18–19; Isaiah 36–37',
    related: ['m-sennacherib'],
  },
  {
    id: 'h-jeremiah',
    lane: 'hebrew',
    year: -627,
    endYear: -580,
    approx: true,
    title: 'Jeremiah',
    source: 'Jeremiah',
  },
  {
    id: 'h-josiah',
    lane: 'hebrew',
    year: -622,
    title: 'Josiah\u2019s reform',
    description: 'A book of the Law is found in the Temple; worship is centralised in Jerusalem.',
    source: '2 Kings 22–23',
  },
  {
    id: 'h-first-deportation',
    lane: 'hebrew',
    year: -597,
    title: 'First deportation to Babylon',
    description: 'Jehoiachin and the elite, including Ezekiel, are taken to Babylon.',
    source: '2 Kings 24; Ezekiel 1',
  },
  {
    id: 'h-jerusalem-fall',
    lane: 'hebrew',
    year: -586,
    title: 'Jerusalem and the Temple destroyed',
    source: '2 Kings 25; Lamentations',
    related: ['m-nebuchadnezzar'],
  },
  {
    id: 'h-exile',
    lane: 'hebrew',
    year: -586,
    endYear: -538,
    title: 'Babylonian Exile',
    description: 'Ezekiel and Daniel; the Psalms of exile (\u201cBy the rivers of Babylon\u201d).',
    source: 'Ezekiel; Daniel; Psalm 137',
    related: ['m-nebuchadnezzar'],
  },
  {
    id: 'h-return',
    lane: 'hebrew',
    year: -538,
    title: 'Cyrus\u2019 decree; return under Zerubbabel',
    source: 'Ezra 1–2; Isaiah 45:1',
    related: ['m-cyrus'],
  },
  {
    id: 'h-second-temple',
    lane: 'hebrew',
    year: -516,
    title: 'Second Temple completed',
    source: 'Ezra 6; Haggai; Zechariah',
  },
  {
    id: 'h-esther',
    lane: 'hebrew',
    year: -479,
    approx: true,
    title: 'Esther at the Persian court',
    source: 'Esther',
    related: ['m-xerxes'],
  },
  {
    id: 'h-ezra-nehemiah',
    lane: 'hebrew',
    year: -458,
    endYear: -433,
    title: 'Ezra and Nehemiah',
    description: 'Ezra teaches the Law; Nehemiah rebuilds the walls of Jerusalem (445).',
    source: 'Ezra 7–10; Nehemiah',
  },
  {
    id: 'h-malachi',
    lane: 'hebrew',
    year: -430,
    approx: true,
    title: 'Malachi, last of the prophets',
    source: 'Malachi',
  },
  {
    id: 'h-septuagint',
    lane: 'hebrew',
    year: -250,
    approx: true,
    title: 'Septuagint begun in Alexandria',
    description: 'The Torah is translated into Greek; this becomes the Bible of the early Church.',
  },
  {
    id: 'h-maccabees',
    lane: 'hebrew',
    year: -167,
    endYear: -160,
    title: 'Maccabean revolt',
    description: 'Antiochus IV desecrates the Temple; Judas Maccabeus rededicates it in 164 (Hanukkah).',
    source: '1–2 Maccabees; Daniel 11',
  },
  {
    id: 'h-qumran',
    lane: 'hebrew',
    year: -150,
    endYear: 68,
    approx: true,
    title: 'Qumran community; Dead Sea Scrolls written',
    related: ['h-dss-found'],
  },
  {
    id: 'h-hasmonean',
    lane: 'hebrew',
    year: -140,
    endYear: -37,
    title: 'Hasmonean kingdom',
  },
  {
    id: 'h-pompey',
    lane: 'hebrew',
    year: -63,
    title: 'Pompey takes Jerusalem',
    description: 'Judea comes under Roman control.',
  },
  {
    id: 'h-herod-temple',
    lane: 'hebrew',
    year: -20,
    title: 'Herod rebuilds the Temple',
    description: 'The Temple Jesus knew; its platform and Western Wall still stand.',
  },
  {
    id: 'h-temple-destroyed',
    lane: 'hebrew',
    year: 70,
    title: 'Second Temple destroyed by Titus',
    description: 'End of the sacrificial cult; rabbinic Judaism and the Church go separate ways.',
    related: ['c-jewish-war'],
  },
  {
    id: 'h-masoretes',
    lane: 'hebrew',
    year: 930,
    approx: true,
    title: 'Masoretic Text; Aleppo Codex',
    description: 'Scholars in Tiberias fix the vowels and text of the Hebrew Bible.',
  },
  {
    id: 'h-dss-found',
    lane: 'hebrew',
    year: 1947,
    title: 'Dead Sea Scrolls discovered',
    description: 'Manuscripts a thousand years older than the Masoretic codices confirm the stability of the text.',
  },

  // ───────────────────────── CHRIST & THE CHURCH ─────────────────────────
  {
    id: 'c-birth',
    lane: 'christian',
    year: -5,
    approx: true,
    title: 'Birth of Jesus',
    description: 'Born in Bethlehem before the death of Herod the Great (4 BCE); most estimates fall in 6–4 BCE.',
    source: 'Matthew 1–2; Luke 1–2',
  },
  {
    id: 'c-ministry',
    lane: 'christian',
    year: 27,
    endYear: 30,
    approx: true,
    title: 'John the Baptist; Jesus\u2019 ministry',
    description: 'Baptism in the Jordan, teaching in Galilee, journey to Jerusalem.',
    source: 'Luke 3:1–2',
  },
  {
    id: 'c-crucifixion',
    lane: 'christian',
    year: 30,
    approx: true,
    title: 'Crucifixion and Resurrection',
    description: 'Under Pontius Pilate, at Passover, in 30 or 33 CE.',
    source: 'Matthew 26–28; Mark 14–16; Luke 22–24; John 18–21',
  },
  {
    id: 'c-pentecost',
    lane: 'christian',
    year: 30,
    approx: true,
    title: 'Pentecost; the Jerusalem church',
    source: 'Acts 2',
  },
  {
    id: 'c-paul-conversion',
    lane: 'christian',
    year: 34,
    approx: true,
    title: 'Conversion of Paul',
    source: 'Acts 9; Galatians 1',
  },
  {
    id: 'c-first-journey',
    lane: 'christian',
    year: 46,
    endYear: 48,
    approx: true,
    title: 'Paul\u2019s first missionary journey',
    source: 'Acts 13–14',
  },
  {
    id: 'c-jerusalem-council',
    lane: 'christian',
    year: 49,
    approx: true,
    title: 'Council of Jerusalem',
    description: 'Gentile believers are not required to keep the Mosaic law.',
    source: 'Acts 15',
  },
  {
    id: 'c-paul-letters',
    lane: 'christian',
    year: 50,
    endYear: 62,
    approx: true,
    title: 'Paul\u2019s letters written',
    description: 'From 1 Thessalonians (c. 50) to the prison epistles.',
  },
  {
    id: 'c-nero',
    lane: 'christian',
    year: 64,
    title: 'Nero\u2019s persecution',
    description: 'After the fire of Rome; Peter and Paul are traditionally martyred c. 64–67.',
  },
  {
    id: 'c-jewish-war',
    lane: 'christian',
    year: 70,
    title: 'Fall of Jerusalem; Gospel of Mark',
    description: 'Mark is usually dated around the Jewish War (c. 65–75).',
  },
  {
    id: 'c-gospels',
    lane: 'christian',
    year: 80,
    endYear: 95,
    approx: true,
    title: 'Matthew, Luke–Acts, John',
  },
  {
    id: 'c-revelation',
    lane: 'christian',
    year: 95,
    approx: true,
    title: 'Revelation written',
    description: 'John on Patmos, under Domitian.',
  },
  {
    id: 'c-ignatius',
    lane: 'christian',
    year: 110,
    approx: true,
    title: 'Ignatius of Antioch martyred',
  },
  {
    id: 'c-polycarp',
    lane: 'christian',
    year: 155,
    approx: true,
    title: 'Martyrdom of Polycarp',
  },
  {
    id: 'c-justin',
    lane: 'christian',
    year: 165,
    approx: true,
    title: 'Justin Martyr',
    description: 'Philosopher-apologist executed in Rome.',
  },
  {
    id: 'c-irenaeus',
    lane: 'christian',
    year: 180,
    approx: true,
    title: 'Irenaeus, Against Heresies',
    description: 'Defends the fourfold Gospel and apostolic succession.',
  },
  {
    id: 'c-tertullian',
    lane: 'christian',
    year: 200,
    approx: true,
    title: 'Tertullian',
    description: 'First major Latin theologian; coins the word \u201cTrinity\u201d.',
  },
  {
    id: 'c-origen',
    lane: 'christian',
    year: 230,
    approx: true,
    title: 'Origen of Alexandria',
    description: 'Biblical scholar; compiles the Hexapla.',
  },
  {
    id: 'c-diocletian',
    lane: 'christian',
    year: 303,
    endYear: 311,
    title: 'The Great Persecution',
  },
  {
    id: 'c-constantine',
    lane: 'christian',
    year: 312,
    title: 'Constantine; Edict of Milan (313)',
    description: 'Victory at the Milvian Bridge; Christianity is legalised.',
  },
  {
    id: 'c-nicaea',
    lane: 'christian',
    year: 325,
    title: 'Council of Nicaea',
    description: 'The Son is \u201cof one substance\u201d with the Father; Arius condemned.',
  },
  {
    id: 'c-athanasius',
    lane: 'christian',
    year: 367,
    title: 'Athanasius lists the 27 NT books',
    source: 'Festal Letter 39',
  },
  {
    id: 'c-constantinople',
    lane: 'christian',
    year: 381,
    title: 'Council of Constantinople',
    description: 'The Nicene Creed in its final form.',
  },
  {
    id: 'c-augustine',
    lane: 'christian',
    year: 396,
    endYear: 430,
    title: 'Augustine, bishop of Hippo',
    description: 'Confessions; The City of God.',
  },
  {
    id: 'c-vulgate',
    lane: 'christian',
    year: 405,
    title: 'Jerome completes the Vulgate',
  },
  {
    id: 'c-chalcedon',
    lane: 'christian',
    year: 451,
    title: 'Council of Chalcedon',
    description: 'Christ is one person in two natures.',
  },
  {
    id: 'c-benedict',
    lane: 'christian',
    year: 529,
    title: 'Benedict founds Monte Cassino',
    description: 'The Rule that shapes Western monasticism.',
  },
  {
    id: 'c-gregory',
    lane: 'christian',
    year: 590,
    endYear: 604,
    title: 'Gregory the Great',
    description: 'Sends Augustine of Canterbury to England (597).',
  },
  {
    id: 'c-china',
    lane: 'christian',
    year: 635,
    title: 'Church of the East reaches China',
  },
  {
    id: 'c-charlemagne',
    lane: 'christian',
    year: 800,
    title: 'Charlemagne crowned in Rome',
  },
  {
    id: 'c-slavs',
    lane: 'christian',
    year: 863,
    title: 'Cyril and Methodius among the Slavs',
  },
  {
    id: 'c-rus',
    lane: 'christian',
    year: 988,
    title: 'Baptism of Kievan Rus\u2019',
  },
  {
    id: 'c-schism',
    lane: 'christian',
    year: 1054,
    title: 'Great Schism East–West',
  },
  {
    id: 'c-crusade',
    lane: 'christian',
    year: 1095,
    title: 'First Crusade called',
  },
  {
    id: 'c-francis',
    lane: 'christian',
    year: 1209,
    title: 'Franciscan order founded',
  },
  {
    id: 'c-aquinas',
    lane: 'christian',
    year: 1274,
    title: 'Thomas Aquinas dies',
    description: 'Summa Theologiae left unfinished.',
  },
  {
    id: 'c-wycliffe',
    lane: 'christian',
    year: 1382,
    title: 'Wycliffe Bible in English',
  },
  {
    id: 'c-hus',
    lane: 'christian',
    year: 1415,
    title: 'Jan Hus burned at Constance',
  },
  {
    id: 'c-luther',
    lane: 'christian',
    year: 1517,
    title: 'Luther\u2019s Ninety-five Theses',
    description: 'The Reformation begins in Wittenberg.',
    related: ['w-printing'],
  },
  {
    id: 'c-anabaptists',
    lane: 'christian',
    year: 1525,
    title: 'Anabaptist movement begins',
    description: 'Believers\u2019 baptism in Zürich.',
  },
  {
    id: 'c-tyndale',
    lane: 'christian',
    year: 1526,
    title: 'Tyndale\u2019s English New Testament',
  },
  {
    id: 'c-england',
    lane: 'christian',
    year: 1534,
    title: 'Church of England breaks with Rome',
  },
  {
    id: 'c-calvin',
    lane: 'christian',
    year: 1536,
    title: 'Calvin\u2019s Institutes; Geneva',
  },
  {
    id: 'c-jesuits',
    lane: 'christian',
    year: 1540,
    title: 'Jesuit order approved',
  },
  {
    id: 'c-trent',
    lane: 'christian',
    year: 1545,
    endYear: 1563,
    title: 'Council of Trent',
    description: 'The Catholic Reformation.',
  },
  {
    id: 'c-kjv',
    lane: 'christian',
    year: 1611,
    title: 'King James Bible',
  },
  {
    id: 'c-pilgrims',
    lane: 'christian',
    year: 1620,
    title: 'Pilgrims found Plymouth',
  },
  {
    id: 'c-wesley',
    lane: 'christian',
    year: 1738,
    title: 'Wesley\u2019s Aldersgate experience',
    description: 'Methodism and the Evangelical Revival.',
  },
  {
    id: 'c-carey',
    lane: 'christian',
    year: 1793,
    title: 'William Carey sails to India',
    description: 'The modern missionary movement.',
  },
  {
    id: 'c-bible-society',
    lane: 'christian',
    year: 1804,
    title: 'British & Foreign Bible Society',
  },
  {
    id: 'c-vatican1',
    lane: 'christian',
    year: 1870,
    title: 'First Vatican Council',
    description: 'Papal infallibility defined.',
  },
  {
    id: 'c-azusa',
    lane: 'christian',
    year: 1906,
    title: 'Azusa Street Revival',
    description: 'Birth of global Pentecostalism.',
  },
  {
    id: 'c-edinburgh',
    lane: 'christian',
    year: 1910,
    title: 'Edinburgh Missionary Conference',
  },
  {
    id: 'c-wcc',
    lane: 'christian',
    year: 1948,
    title: 'World Council of Churches',
  },
  {
    id: 'c-vatican2',
    lane: 'christian',
    year: 1962,
    endYear: 1965,
    title: 'Second Vatican Council',
  },
  {
    id: 'c-lausanne',
    lane: 'christian',
    year: 1974,
    title: 'Lausanne Congress',
  },
  {
    id: 'c-global-south',
    lane: 'christian',
    year: 2000,
    approx: true,
    title: 'Centre of Christianity shifts south',
    description: 'The majority of Christians now live in Africa, Asia and Latin America.',
  },
  {
    id: 'c-francis',
    lane: 'christian',
    year: 2013,
    title: 'Pope Francis elected',
  },
  {
    id: 'c-leo',
    lane: 'christian',
    year: 2025,
    title: 'Pope Leo XIV elected',
  },
]
